### ISSUE TITLE
Error on importing the template

### ISSUE THREAD

**Issue by jokay** [vivanov-dp/zabbix-docker-template#1]
When I try to import the template on Zabbix `5.0.2` I get the following error:

```sh
Trigger "Docker: Failed to fetch info data (or no data for 30m)" depends on trigger "Docker: Service is down", which does not exist.
```

**Comment by vivanov-dp** [comment]
Hi, 
Can  you tell me if this one persists ? It sounds like a Zabbix hiccup during import

**Comment by x-jokay** [comment]
On Zabbix `5.0.3` I still get the error.

![zabbix-agent-import-failed](https://user-images.githubusercontent.com/18613935/91698380-e3de0980-eb72-11ea-869b-726e8f30308d.png)

**Comment by jokay** [comment]
Now it works on Zabbix `5.0.3`, issue closed :wink:
