### ISSUE TITLE
No curl available when using official zabbix-agent Docker image (zabbix/zabbix-agent:alpine-5.0-latest)

### ISSUE THREAD

**Issue by jokay** [vivanov-dp/zabbix-docker-template#2]
When using the official zabbix-agent Docker image [zabbix/zabbix-agent:alpine-5.0-latest](https://hub.docker.com/r/zabbix/zabbix-agent) there is no `curl` available but `wget` can be used.

A second [docker_template.conf](https://github.com/vivanov-dp/zabbix-docker-template/blob/master/docker_template.conf) using the `wget` command instead of `curl` may be useful?

**Comment by vivanov-dp** [comment]
Hi, sorry for taking so long to respond ...
Sure, I can add one with wget

**Comment by jokay** [comment]
I'm not sure if it's possible to connect to a `unix-socket` using `wget`?

**Comment by vivanov-dp** [comment]
Not directly I think ... 
There are some options, but all of them require a bit of setting up ... does the zabbix docker image have ncat or socat ? 

Or at the very least the API can be accessed via HTTP - I don't do that by default because it might involve more steps, even on the local host

**Comment by jokay** [comment]
No `ncat` or `socat` available.

**Comment by jokay** [comment]
I would prefer to have to only mount `/var/run/docker.sock` to get it work as well.

**Comment by jokay** [comment]
I will try [this](https://www.zabbix.com/integrations/docker), it may work for us.

**Comment by vivanov-dp** [comment]
Sure, if you can choose to use agent v2, docker monitoring comes built-in.

If that doesn't work - I was thinking of creating yourself a custom image, based on the Zabbix one, with curl installed and publishing that to a docker repo. 
It will help avoid additional provisioning of the installed agent.
